#!/bin/bash

echo "🔧 REGRAS FIRESTORE TEMPORÁRIAS PARA DEBUG"
echo "==========================================="
echo ""
echo "🚨 ATENÇÃO: Estas são regras TEMPORÁRIAS mais permissivas"
echo "para identificar a causa do erro de permissões."
echo ""
echo "📋 COPIE o conteúdo abaixo e SUBSTITUA no Firebase Console:"
echo ""
echo "🔗 Firebase Console: https://console.firebase.google.com"
echo "📍 Caminho: Firestore Database > Rules"
echo ""
echo "==================== INICIO DAS REGRAS ===================="
cat firestore.rules
echo "==================== FIM DAS REGRAS ======================="
echo ""
echo "⚡ APÓS APLICAR ESTAS REGRAS:"
echo "1. Aguarde 2-3 minutos para propagação"
echo "2. Teste criar uma avaliação temática"
echo "3. Se funcionar: o problema era na validação"
echo "4. Se não funcionar: o problema é mais básico"
echo ""
echo "📝 IMPORTANTE:"
echo "Após identificar o problema, RESTAURE as regras com validação"
echo "completa para manter a segurança em produção!"